import { chromium } from 'playwright';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import http from 'node:http';
import crypto from 'node:crypto';
import { execFileSync } from 'node:child_process';

const root=path.resolve(process.cwd());
const corte=process.env.CORTE_DATA||'2026-08-10';
const slug=corte.replaceAll('-','_');
const expectedHex=Number(process.env.EXPECTED_HEX||1554);
const indexFile=path.join(root,'index.html');
const preDir=path.join(root,'dados','precalculados');
const matDir=path.join(root,'dados','materializados',slug);
const rawDir=path.join(root,`capturas_fontes_${slug}`,'cadastur_ict');
const outDir=path.join(root,'resultados_indices',corte);
const docsDir=path.join(root,'docs');
const backupDir=path.join(docsDir,'BACKUP_index');
for(const d of [preDir,matDir,rawDir,outDir,docsDir,backupDir])fs.mkdirSync(d,{recursive:true});
if(!fs.existsSync(indexFile))throw new Error('index.html não encontrado. Execute este script na raiz C:\\joaju-ms.');

const SOURCES={
 hospedagem:{id:'cadastur_hospedagem',packageId:'d2333d1b-db1e-438b-955a-028db80a031e',label:'Meios de Hospedagem',page:'https://dados.turismo.gov.br/pt_BR/dataset/meios-de-hospedagem',patterns:[/meios?.*hosped/i,/hospedagem/i],fallback:[{url:'https://dados.turismo.gov.br/dataset/d2333d1b-db1e-438b-955a-028db80a031e/resource/7e385ec2-57d8-446c-9cc0-f5f7dadd1fdf/download/meios-de-hospedagem-2-trimestre-2026.xlsx',periodo:'2º trimestre 2026'}]},
 agencia:{id:'agencia',packageId:'5a324238-184a-4103-bfaa-bb998aa10328',label:'Agência de Turismo',page:'https://dados.turismo.gov.br/pt_BR/dataset/agencia-de-turismo',patterns:[/ag[eê]ncia.*turismo/i,/agencia.*turismo/i],fallback:[{url:'https://dados.turismo.gov.br/dataset/agencia-de-turismo/resource/bac392e7-18e0-49b7-bbb3-4d54628a3fec/download/agencia-de-turismo-1-trimestre-2026.xlsx',periodo:'1º trimestre 2026 · contingência'}]},
 guia:{id:'guia',packageId:'04c5fd1e-8816-42fb-b618-73287850829b',label:'Guia de Turismo',page:'https://dados.turismo.gov.br/pt_BR/dataset/prestadores-de-servicos-turisticos-guia-turismo_2',patterns:[/guia.*turismo/i],fallback:[{url:'https://dados.turismo.gov.br/dataset/prestadores-de-servicos-turisticos-guia-turismo_2/resource/d5e2ebf6-fc12-4cf3-94d0-8b31789f18e7/download/guia-de-turismo-2-trimestre-2026.xlsx',periodo:'2º trimestre 2026'}]},
 transportadora:{id:'transportadora',packageId:'3f766daa-2df8-44be-acee-91f520443516',label:'Transportadora Turística',page:'https://dados.turismo.gov.br/pt_BR/dataset/transportadora-turistica',patterns:[/transportadora.*tur[ií]st/i,/transportadora.*turist/i],fallback:[{url:'https://dados.turismo.gov.br/dataset/transportadora-turistica/resource/faed2692-81c1-425e-b5c8-fbbb065a13c2/download/transportadora-turistica-2-trimestre-2026.xlsx',periodo:'2º trimestre 2026'}]}
};

const sha256=b=>crypto.createHash('sha256').update(b).digest('hex');
const shaFile=f=>sha256(fs.readFileSync(f));
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function norm(s){return String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();}
function resourceScore(r){const t=norm(`${r.name||''} ${r.description||''} ${r.last_modified||''} ${r.url||''}`);let s=0;if(/segundo trimestre.*2026|2.? trimestre.*2026|2-trimestre-2026/.test(t))s+=120;if(/primeiro trimestre.*2026|1.? trimestre.*2026|1-trimestre-2026/.test(t))s+=90;if(/2026/.test(t))s+=50;if(/xlsx/i.test(String(r.format||''))||/\.xlsx(?:\?|$)/i.test(String(r.url||'')))s+=20;return s;}
async function fetchJson(url,timeout=35000){const c=new AbortController(),tm=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{headers:{'user-agent':'JOAJU-MS/1.8 ICT materializer'},signal:c.signal});if(!r.ok)throw new Error(`HTTP ${r.status}`);return await r.json();}finally{clearTimeout(tm)}}
async function fetchBuffer(url,timeout=90000){const c=new AbortController(),tm=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{headers:{'user-agent':'JOAJU-MS/1.8 ICT materializer'},signal:c.signal,redirect:'follow'});if(!r.ok)throw new Error(`HTTP ${r.status}`);return Buffer.from(await r.arrayBuffer());}finally{clearTimeout(tm)}}
function curlBuffer(url){const tmp=path.join(rawDir,`.curl_${process.pid}_${Date.now()}.tmp`);try{execFileSync('curl.exe',['-L','--fail','--silent','--show-error','--retry','3','--retry-all-errors','--connect-timeout','25','--max-time','180','-A','JOAJU-MS/1.8 ICT materializer','-o',tmp,url],{stdio:'pipe'});return fs.readFileSync(tmp)}finally{try{fs.unlinkSync(tmp)}catch{}}}
async function robustBuffer(url){try{return await fetchBuffer(url)}catch(e){if(process.platform==='win32'){try{return curlBuffer(url)}catch(c){throw new Error(`${e.message}; curl: ${String(c?.stderr||c?.message||c).trim()}`)}}throw e}}
function isXlsxBuffer(b){return b?.length>100&&b[0]===0x50&&b[1]===0x4b;}
function downloadsDirs(){const ds=new Set();for(const base of [process.env.USERPROFILE,os.homedir()])if(base)ds.add(path.join(base,'Downloads'));ds.add(rawDir);return [...ds].filter(d=>fs.existsSync(d));}
function findLocal(src){const c=[];for(const dir of downloadsDirs()){for(const name of fs.readdirSync(dir)){const f=path.join(dir,name);if(!fs.statSync(f).isFile()||!/[.]xlsx$/i.test(name))continue;if(src.patterns.some(p=>p.test(name)))c.push(f);}}return c.sort((a,b)=>fs.statSync(b).mtimeMs-fs.statSync(a).mtimeMs)[0]||null;}
async function discoverRemote(src){try{const j=await fetchJson(`https://dados.turismo.gov.br/api/3/action/package_show?id=${encodeURIComponent(src.packageId)}`,45000);const rs=[...(j?.result?.resources||[])].filter(r=>/xlsx|xls/i.test(String(r.format||''))||/\.xlsx(?:\?|$)/i.test(String(r.url||''))).sort((a,b)=>resourceScore(b)-resourceScore(a));if(rs.length)return {url:rs[0].url,periodo:rs[0].name||'recurso mais recente identificado pela API CKAN',resourceId:rs[0].id||null,lastModified:rs[0].last_modified||rs[0].metadata_modified||null,via:'API CKAN'};}catch(e){console.log(`  API CKAN indisponível · ${src.label} · ${e.message||e}`)}return null;}
async function obtain(key){const src=SOURCES[key];const existing=findLocal(src);if(existing){const b=fs.readFileSync(existing);if(isXlsxBuffer(b)){const dest=path.join(rawDir,`${key}_${path.basename(existing).replace(/[^a-zA-Z0-9._-]+/g,'_')}`);if(path.resolve(existing)!==path.resolve(dest))fs.copyFileSync(existing,dest);console.log(`  LOCAL · ${src.label} · ${existing}`);return {key,file:dest,sourceFile:existing,sourcePage:src.page,periodo:/2.?trimestre.*2026/i.test(path.basename(existing))?'2º trimestre 2026':'arquivo oficial local',via:'Downloads',sha256:shaFile(dest)};}}
 const candidates=[];const remote=await discoverRemote(src);if(remote)candidates.push(remote);candidates.push(...src.fallback.map(x=>({...x,via:'rota oficial direta'})));
 let last='';for(const r of candidates){try{console.log(`  baixando · ${src.label} · ${r.periodo}`);const b=await robustBuffer(r.url);if(!isXlsxBuffer(b))throw new Error('resposta não é XLSX/ZIP válido');const dest=path.join(rawDir,`${key}_${path.basename(new URL(r.url).pathname)||key+'.xlsx'}`);fs.writeFileSync(dest,b);return {key,file:dest,url:r.url,sourcePage:src.page,periodo:r.periodo,resourceId:r.resourceId||null,lastModified:r.lastModified||null,via:r.via,sha256:sha256(b)};}catch(e){last=String(e.message||e);console.log(`  falhou · ${src.label} · ${last}`);await sleep(400)}}return {key,error:last||'nenhum arquivo disponível',sourcePage:src.page};}

function patchIndexForICT(){let html=fs.readFileSync(indexFile,'utf8');const blocker="  throw new Error('ICT ainda não deve ser materializado. A metodologia está sendo ampliada para incorporar acolhimento e serviços ao visitante com cobertura documentada. Feche o protocolo ICT revisado antes do corte final.');\n";let changed=false;if(html.includes(blocker)){const backup=path.join(backupDir,`BACKUP_index_pre_ICT_${corte}.html`);if(!fs.existsSync(backup))fs.copyFileSync(indexFile,backup);html=html.replace(blocker,'');changed=true;}
 if(changed){fs.writeFileSync(indexFile,html,'utf8');console.log(`Bloqueio legado ICT removido · backup preservado em docs\\BACKUP_index`);}else if(!html.includes('async function calculateICT250()'))throw new Error('calculateICT250 não encontrado no index.html atual');
}
function mime(file){const e=path.extname(file).toLowerCase();return ({'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.json':'application/json; charset=utf-8','.geojson':'application/geo+json; charset=utf-8','.css':'text/css; charset=utf-8','.xlsx':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','.webmanifest':'application/manifest+json'})[e]||'application/octet-stream'}
function startServer(){return new Promise((resolve,reject)=>{const server=http.createServer((req,res)=>{try{const u=new URL(req.url,'http://127.0.0.1');const rel=decodeURIComponent(u.pathname).replace(/^\/+/, '')||'index.html';const file=path.resolve(root,rel);if(!file.startsWith(root+path.sep)&&file!==indexFile){res.writeHead(403);res.end('forbidden');return}if(!fs.existsSync(file)||fs.statSync(file).isDirectory()){res.writeHead(404);res.end('not found');return}res.writeHead(200,{'Content-Type':mime(file),'Cache-Control':'no-store'});fs.createReadStream(file).pipe(res)}catch(e){res.writeHead(500);res.end(String(e))}});server.once('error',reject);server.listen(0,'127.0.0.1',()=>resolve({server,port:server.address().port}))})}
async function launchBrowser(){try{return await chromium.launch({headless:true})}catch(first){const candidates=process.platform==='win32'?[process.env['PROGRAMFILES']&&path.join(process.env['PROGRAMFILES'],'Microsoft','Edge','Application','msedge.exe'),process.env['PROGRAMFILES(X86)']&&path.join(process.env['PROGRAMFILES(X86)'],'Microsoft','Edge','Application','msedge.exe'),process.env['PROGRAMFILES']&&path.join(process.env['PROGRAMFILES'],'Google','Chrome','Application','chrome.exe'),process.env['PROGRAMFILES(X86)']&&path.join(process.env['PROGRAMFILES(X86)'],'Google','Chrome','Application','chrome.exe')].filter(Boolean):[];for(const executablePath of candidates)if(fs.existsSync(executablePath)){console.log(`Navegador local · ${executablePath}`);return chromium.launch({headless:true,executablePath})}throw first}}
function validateGrid(grid){if(grid?.type!=='FeatureCollection'||!Array.isArray(grid.features))throw new Error('Malha territorial inválida');if(grid.features.length!==expectedHex)throw new Error(`Malha territorial contém ${grid.features.length}. Esperado ${expectedHex}.`);const ids=new Set(grid.features.map(f=>String(f?.properties?.hex_id||'')));if(ids.size!==expectedHex||ids.has(''))throw new Error('hex_id ausente ou duplicado na malha');return ids}
function validateICT(data,ids){if(data?.type!=='FeatureCollection'||!Array.isArray(data.features)||data.features.length!==ids.size)throw new Error(`ICT não contém ${ids.size} hexágonos`);const seen=new Set();for(const f of data.features){const id=String(f?.properties?.hex_id||'');if(!ids.has(id)||seen.has(id))throw new Error(`ICT com hex_id inválido/duplicado ${id}`);seen.add(id);const v=Number(f?.properties?.ict_100);if(!Number.isFinite(v)||v<0||v>100)throw new Error(`ICT inválido em ${id}: ${f?.properties?.ict_100}`)}}
function jsWrapper(id,data){return `window.ATLAS_DATA=window.ATLAS_DATA||{};\nwindow.ATLAS_DATA[${JSON.stringify(id)}]=${JSON.stringify(data)};\n`}
function patchManifest(entries){let html=fs.readFileSync(indexFile,'utf8');const m=html.match(/const DATA_MANIFEST = (\{.*?\});\nwindow\.ATLAS_DATA/s);if(!m)return false;const manifest=JSON.parse(m[1]);Object.assign(manifest,entries);html=html.replace(m[0],`const DATA_MANIFEST = ${JSON.stringify(manifest)};\nwindow.ATLAS_DATA`);fs.writeFileSync(indexFile,html,'utf8');return true}

console.log(`JOAJU MS · materialização isolada ICT · Cadastur · corte ${corte}`);
console.log('Somente ICT. Não executa ComexStat, PIN/MS, educação, ISA, IPAE nem a materialização geral.');
console.log('Procurando os quatro conjuntos oficiais necessários ao ICT...');
patchIndexForICT();
const acquired={};for(const k of ['hospedagem','agencia','guia','transportadora'])acquired[k]=await obtain(k);
const missing=Object.values(acquired).filter(x=>x.error);
if(missing.length){const lines=[`JOAJU MS · ICT · arquivos Cadastur ainda necessários · corte ${corte}`,'','Baixe os XLSX oficiais e salve-os em Downloads. Não renomeie se não for necessário. Depois execute novamente:','node scripts\\materializar_ict_cadastur_250km2.mjs',''];for(const x of missing){const src=SOURCES[x.key];lines.push(`${src.label}\n${src.page}\n`)}const instr=path.join(docsDir,`INSTRUCAO_ICT_CADASTUR_${corte}.txt`);fs.writeFileSync(instr,lines.join('\n'),'utf8');console.error(`\nFALHA ICT · faltam ${missing.length} conjunto(s) Cadastur. Nenhum valor foi inventado.`);for(const x of missing)console.error(`  PENDENTE · ${SOURCES[x.key].label}`);console.error(`Instruções · ${path.relative(root,instr)}`);process.exit(1)}

const {server,port}=await startServer();const browser=await launchBrowser();const context=await browser.newContext({viewport:{width:1440,height:900}});const page=await context.newPage();page.setDefaultTimeout(240000);page.on('console',m=>{const t=m.text();if(/ICT|Cadastur|Malha|Falha|erro/i.test(t))console.log('[browser] '+t)});page.on('pageerror',e=>console.error('[pageerror] '+e.message));
try{
 const url=`http://127.0.0.1:${port}/index.html`;console.log(`Atlas local · ${url}`);await page.goto(url,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>typeof window.calculateICT250==='function'&&typeof window.loadMasterTerritorialGrid250==='function'&&typeof window.xlsxRowsFromBuffer==='function'&&typeof window.rowsToOfficialGeoJSON==='function',{timeout:180000});
 const rel=x=>path.relative(root,x.file).replaceAll('\\','/');
 const parsed=await page.evaluate(async spec=>{async function rows(url,label){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error(`${label} HTTP ${r.status}`);const part=await xlsxRowsFromBuffer(await r.arrayBuffer());part.forEach(x=>x.__conjunto_cadastur=label);return part}const hrows=await rows(spec.hosp.url,spec.hosp.label);let srows=[];for(const x of spec.serv)srows=srows.concat(await rows(x.url,x.label));const hcfg=configs.find(c=>c.id==='cadastur_hospedagem'),scfg=configs.find(c=>c.id==='cadastur_agencias_guias');if(!hcfg||!scfg)throw new Error('Configuração Cadastur não encontrada no Atlas');const hosp=await rowsToOfficialGeoJSON(hrows,hcfg),serv=await rowsToOfficialGeoJSON(srows,scfg);return {hosp,serv,hrows:hrows.length,srows:srows.length}}, {hosp:{url:'/'+rel(acquired.hospedagem),label:`Meios de Hospedagem · ${acquired.hospedagem.periodo}`},serv:['agencia','guia','transportadora'].map(k=>({url:'/'+rel(acquired[k]),label:`${SOURCES[k].label} · ${acquired[k].periodo}`}))});
 if(!parsed.hosp?.features?.length)throw new Error('Meios de hospedagem não produziram sínteses municipais de MS');if(!parsed.serv?.features?.length)throw new Error('Serviços Cadastur não produziram sínteses municipais de MS');
 parsed.hosp.atlas_metadata={fonte:'Ministério do Turismo · Cadastur',corte,recursos:[acquired.hospedagem],linhas_lidas:parsed.hrows,metodo:'síntese municipal, sem publicação de dados individuais'};parsed.serv.atlas_metadata={fonte:'Ministério do Turismo · Cadastur',corte,recursos:['agencia','guia','transportadora'].map(k=>acquired[k]),linhas_lidas:parsed.srows,metodo:'agências + guias + transportadoras, síntese municipal'};
 const hGeo=path.join(matDir,'cadastur_hospedagem.geojson'),sGeo=path.join(matDir,'cadastur_agencias_guias.geojson'),hJs=path.join(matDir,'cadastur_hospedagem.js'),sJs=path.join(matDir,'cadastur_agencias_guias.js');fs.writeFileSync(hGeo,JSON.stringify(parsed.hosp),'utf8');fs.writeFileSync(sGeo,JSON.stringify(parsed.serv),'utf8');fs.writeFileSync(hJs,jsWrapper('cadastur_hospedagem',parsed.hosp),'utf8');fs.writeFileSync(sJs,jsWrapper('cadastur_agencias_guias',parsed.serv),'utf8');patchManifest({cadastur_hospedagem:{arquivo:path.relative(root,hJs).replaceAll('\\','/'),registros:parsed.hosp.features.length,sha256:shaFile(hGeo)},cadastur_agencias_guias:{arquivo:path.relative(root,sJs).replaceAll('\\','/'),registros:parsed.serv.features.length,sha256:shaFile(sGeo)}});
 await page.reload({waitUntil:'domcontentloaded'});await page.waitForFunction(()=>typeof window.calculateICT250==='function'&&typeof window.loadMasterTerritorialGrid250==='function');const grid=await page.evaluate(()=>window.loadMasterTerritorialGrid250());const ids=validateGrid(grid);console.log(`Malha territorial · ${grid.features.length} hexágonos`);await page.evaluate(async()=>{const h=await loadEmbeddedLayer('cadastur_hospedagem'),s=await loadEmbeddedLayer('cadastur_agencias_guias');setLayerData('cadastur_hospedagem',h,'capturado');setLayerData('cadastur_agencias_guias',s,'capturado')});
 console.log(`Hospedagem · ${parsed.hosp.features.length} municípios com registros`);console.log(`Serviços Cadastur · ${parsed.serv.features.length} municípios com registros`);console.log('Calculando ICT...');const data=await page.evaluate(()=>window.calculateICT250());validateICT(data,ids);
 const crosswalk=await page.evaluate(()=>({metadata:window.hexMunicipalMetadata||hexMunicipalMetadata,rows:Object.fromEntries(hexMunicipalCrosswalk)}));
 if(Number(crosswalk?.metadata?.n_hexagonos)!==expectedHex||Object.keys(crosswalk?.rows||{}).length!==expectedHex)throw new Error(`Crosswalk município–hexágono incompleto após ICT: ${Object.keys(crosswalk?.rows||{}).length}/${expectedHex}`);
 const crosswalkFile=path.join(preDir,'hex_municipios_crosswalk_250km2.json');fs.writeFileSync(crosswalkFile,JSON.stringify(crosswalk),'utf8');console.log(`Crosswalk · ${path.relative(root,crosswalkFile)} · ${crosswalk.metadata.n_hexagonos} hexágonos`);
 const values=data.features.map(f=>Number(f.properties.ict_100));const min=Math.min(...values),max=Math.max(...values),mean=values.reduce((a,b)=>a+b,0)/values.length,positive=values.filter(v=>v>0).length;const output={...data,atlas_metadata:{...(data.atlas_metadata||{}),corte_dados:corte,status_materializacao:'materializado_isoladamente',fontes:'Ministério do Turismo · Cadastur',componentes:'50% meios de hospedagem + 50% agências, guias e transportadoras',recursos_oficiais:Object.fromEntries(Object.entries(acquired).map(([k,v])=>[k,{periodo:v.periodo,via:v.via,sha256:v.sha256,url:v.url||null,sourcePage:v.sourcePage}]))}};
 const preFile=path.join(preDir,'ict_250km2.geojson'),dated=path.join(outDir,'ict_capacidade_turistica_250km2.geojson');fs.writeFileSync(preFile,JSON.stringify(output),'utf8');fs.writeFileSync(dated,JSON.stringify(output),'utf8');const periods=Object.fromEntries(Object.entries(acquired).map(([k,v])=>[k,v.periodo]));const report={project:'JOAJU MS',cut:corte,index:'ICT',status:'PASS',hexagons:output.features.length,ict_min:Number(min.toFixed(2)),ict_mean:Number(mean.toFixed(2)),ict_max:Number(max.toFixed(2)),hexagons_positive:positive,hospedagem_municipios:parsed.hosp.features.length,servicos_municipios:parsed.serv.features.length,raw_rows_hospedagem:parsed.hrows,raw_rows_servicos:parsed.srows,periodos:periods,formula:'100 × (0,50 hospedagem formal + 0,50 serviços Cadastur)',servicos_operacionalizados:'Agências de Turismo + Guias de Turismo + Transportadoras Turísticas',escala:'contexto municipal ponderado pela interseção município–hexágono',positional_adequacy_pct:50,precomputed:path.relative(root,preFile).replaceAll('\\','/'),sha256:shaFile(preFile),generated_at:new Date().toISOString(),note:'Materialização isolada do ICT. Restaurantes, cafeterias e bares permanecem camada contextual separada e não entram na fórmula congelada do ICT.'};const reportFile=path.join(docsDir,`VALIDACAO_ICT_250KM2_${corte}.json`);fs.writeFileSync(reportFile,JSON.stringify(report,null,2)+'\n','utf8');console.log(`ICT · PASS · ${output.features.length} hexágonos`);console.log(`ICT 100 · mínimo ${report.ict_min} · média ${report.ict_mean} · máximo ${report.ict_max}`);console.log(`Hexágonos com ICT > 0 · ${positive}/${output.features.length}`);console.log(`Períodos · hospedagem ${periods.hospedagem} · agência ${periods.agencia} · guia ${periods.guia} · transportadora ${periods.transportadora}`);console.log(`GeoJSON · ${path.relative(root,preFile)}`);console.log(`Validação · ${path.relative(root,reportFile)}`);
}catch(e){console.error(`\nFALHA ICT · ${e?.stack||e}`);process.exitCode=1}finally{await context.close().catch(()=>{});await browser.close().catch(()=>{});await new Promise(r=>server.close(r))}
